export const ANSWER_LIST = [
  "nodes",
  "types",
  "float",
  "async",
  "await",
  "array",
  "stack",
  "queue",
  "const",
  "query",
  "fetch",
  "flask",
  "debug",
  "short",
  "react",
  "redux",
  "astro",
  "state",
  "cobol",
  "proxy",
  "cache",
  "style",
  "print",
  "graph",
  "index",
  "class",
  "scope",
  "local",
  "block",
  "space",
  "linux",
  "input",
  "event",
  "cloud",
  "route",
  "loops",
  "child",
  "unity",
  "logic",
  "trees",
  "asset",
  "param",
  "mysql",
  "mount",
  "model",
  "break",
  "props",
  "rails",
  "equal",
  "value",
  "defer",
  "parse",
  "purge",
  "reset",
  "digit",
  "enums",
];

export const ANSWERS = [
  {
    word: "nodes",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes.
                  Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },

  {
    word: "types",
    description: `A collection or grouping of data values, usually specified by a set of possible values, 
                  a set of allowed operations on these values, and/or a representation of these values as machine types`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "float",
    description: `A common data type in computer programming that represents a number with a decimal point`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "async",
    description: `An asynchronous operation means that a process operates independently of other processes.
                  By contrast, a synchronous operation runs only as a result of other processes being completed or handed off.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "await",
    description: `A keyword used in programming languages like JavaScript designed to asynchronously wait for tasks to be completed.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "array",
    description: `An array is a data structure that holds similar, related data in a sequential order. Each value in an array is often 
                  referenced by an index or key.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "stack",
    description: `A linear data structure in which the last elements to be placed in the stack (push) are the first ones to be removed (pop).`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "queue",
    description: `Similar to the stack data structure, the queue places items in a linear and orderly format. The key difference with the stack
                  is that the first elements that are inserted are the ones that are removed when pop() is called.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "const",
    description: `'const' (short for constant) is a keyword seen in many programming languages that declares immutable variables. That means,
                  any variable declared with a 'const' value shall not be modified to any other value.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "query",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "fetch",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "flask",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "debug",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "short",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "react",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "redux",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "astro",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "state",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "cobol",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "proxy",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "cache",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "style",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "print",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "graph",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "index",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "class",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "scope",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "space",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "input",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "local",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "block",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "route",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "linux",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "event",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "cloud",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "loops",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "child",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "unity",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "logic",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "trees",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "asset",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "param",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "mysql",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "mount",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "model",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "break",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "props",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "rails",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "equal",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "value",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "defer",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "parse",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "purge",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "reset",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "digit",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
  {
    word: "enums",
    description: `Nodes are a basic data structure which contain data and one or more links to other nodes. Nodes can be used to represent a tree structure or a linked list.`,
    descriptiveImage: "",
    supplementalImage: "",
  },
];
